name: constructo_user
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  get: ^4.7.2
  flutter_localization: ^0.3.3
  pod: ^0.18.0
  intl: ^0.20.2
  table_calendar: ^3.2.0
  collection: ^1.19.1
  flutter_launcher_icons: ^0.14.4
  razorpay_flutter: ^1.4.0
  fluttertoast: ^8.2.12
  http: ^1.4.0
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  get_storage: ^2.1.1
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/mainlogo.jpg"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # example:
  fonts:
    - family: GTEesti
      fonts:
        - asset: assets/fonts/gteestiprodisplay_regular.otf
        - asset: assets/fonts/gteestiprodisplay_medium.otf
          weight: 500
        - asset: assets/fonts/gteestiprodisplay_regular.otf
          weight: 600
        - asset: assets/fonts/gteestiprodisplay_bold.otf
          weight: 700
        - asset: assets/fonts/gteestiprodisplay_medium.otf
          weight: 300
        - asset: assets/fonts/gteestiprodisplay_ultrabold.otf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
